# This file is auto-generated from the current state of the database. Instead
# of editing this file, please use the migrations feature of Active Record to
# incrementally modify your database, and then regenerate this schema definition.
#
# This file is the source Rails uses to define your schema when running `bin/rails
# db:schema:load`. When creating a new database, `bin/rails db:schema:load` tends to
# be faster and is potentially less error prone than running all of your
# migrations from scratch. Old migrations may fail to apply correctly if those
# migrations use external dependencies or application code.
#
# It's strongly recommended that you check this file into your version control system.

ActiveRecord::Schema[7.1].define(version: 2026_06_21_120008) do
  create_table "posts", force: :cascade do |t|
    t.string "ibrahim_eita_send_regards_ahmed_fathi0"
    t.string "ibrahim_eita_send_regards_ahmed_fathi1"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.string "ibrahim_eita_send_regards_ahmed_fathi2"
    t.string "ibrahim_eita_send_regards_ahmed_fathi3"
    t.string "ibrahim_eita_send_regards_ahmed_fathi4"
    t.string "ibrahim_eita_send_regards_ahmed_fathi5"
    t.string "ibrahim_eita_send_regards_ahmed_fathi6"
    t.string "ibrahim_eita_send_regards_ahmed_fathi7"
    t.string "ibrahim_eita_send_regards_ahmed_fathi8"
    t.string "ibrahim_eita_send_regards_ahmed_fathi9"
    t.string "ibrahim_eita_send_regards_ahmed_fathi10"
    t.string "ibrahim_eita_send_regards_ahmed_fathi11"
    t.string "ibrahim_eita_send_regards_ahmed_fathi12"
    t.string "ibrahim_eita_send_regards_ahmed_fathi13"
    t.string "ibrahim_eita_send_regards_ahmed_fathi14"
    t.string "ibrahim_eita_send_regards_ahmed_fathi15"
    t.string "ibrahim_eita_send_regards_ahmed_fathi16"
    t.string "ibrahim_eita_send_regards_ahmed_fathi17"
    t.string "ibrahim_eita_send_regards_ahmed_fathi18"
    t.string "ibrahim_eita_send_regards_ahmed_fathi19"
    t.string "ibrahim_eita_send_regards_ahmed_fathi20"
    t.string "ibrahim_eita_send_regards_ahmed_fathi21"
    t.string "ibrahim_eita_send_regards_ahmed_fathi22"
    t.string "ibrahim_eita_send_regards_ahmed_fathi23"
    t.string "ibrahim_eita_send_regards_ahmed_fathi24"
    t.string "ibrahim_eita_send_regards_ahmed_fathi25"
    t.string "ibrahim_eita_send_regards_ahmed_fathi26"
    t.string "ibrahim_eita_send_regards_ahmed_fathi27"
    t.string "ibrahim_eita_send_regards_ahmed_fathi28"
    t.string "ibrahim_eita_send_regards_ahmed_fathi29"
    t.string "ibrahim_eita_send_regards_ahmed_fathi30"
    t.string "ibrahim_eita_send_regards_ahmed_fathi31"
    t.string "ibrahim_eita_send_regards_ahmed_fathi32"
    t.string "ibrahim_eita_send_regards_ahmed_fathi33"
    t.string "ibrahim_eita_send_regards_ahmed_fathi34"
    t.string "ibrahim_eita_send_regards_ahmed_fathi35"
    t.string "ibrahim_eita_send_regards_ahmed_fathi36"
    t.string "ibrahim_eita_send_regards_renamed_by_noorelmobashar37"
    t.string "ibrahim_eita_send_regards_renamed_by_noorelmobashar38"
    t.string "ibrahim_eita_send_regards_renamed_by_noorelmobashar39"
    t.integer "renamed_by_noorelmobashar40"
    t.string "ibrahim_eita_send_regards_renamed_by_noorelmobashar41"
    t.string "ibrahim_eita_send_regards_renamed_by_noorelmobashar42"
    t.string "ibrahim_eita_send_regards_renamed_by_noorelmobashar43"
    t.string "ibrahim_eita_send_regards_renamed_by_noorelmobashar44"
    t.string "ibrahim_eita_send_regards_renamed_by_noorelmobashar45"
    t.string "ibrahim_eita_send_regards_renamed_by_noorelmobashar46"
    t.string "ibrahim_eita_send_regards_renamed_by_noorelmobashar47"
    t.string "ibrahim_eita_send_regards_renamed_by_noorelmobashar48"
    t.string "ibrahim_eita_send_regards_renamed_by_noorelmobashar49"
    t.string "ibrahim_eita_send_regards_renamed_by_noorelmobashar50"
    t.string "ibrahim_eita_send_regards_renamed_by_noorelmobashar51"
    t.string "ibrahim_eita_send_regards_renamed_by_noorelmobashar52"
    t.string "ibrahim_eita_send_regards_renamed_by_noorelmobashar53"
    t.string "ibrahim_eita_send_regards_renamed_by_noorelmobashar54"
    t.string "ibrahim_eita_send_regards_renamed_by_noorelmobashar55"
    t.string "ibrahim_eita_send_regards_renamed_by_noorelmobashar56"
    t.string "ibrahim_eita_send_regards_renamed_by_noorelmobashar57"
    t.string "ibrahim_eita_send_regards_renamed_by_noorelmobashar58"
    t.string "ibrahim_eita_send_regards_renamed_by_noorelmobashar59"
    t.string "ibrahim_eita_send_regards_renamed_by_noorelmobashar60"
    t.string "ibrahim_eita_send_regards_renamed_by_noorelmobashar61"
    t.string "ibrahim_eita_send_regards_renamed_by_noorelmobashar62"
    t.string "ibrahim_eita_send_regards_renamed_by_noorelmobashar63"
    t.string "ibrahim_eita_send_regards_renamed_by_noorelmobashar64"
    t.string "ibrahim_eita_send_regards_renamed_by_noorelmobashar65"
    t.string "ibrahim_eita_send_regards_renamed_by_noorelmobashar66"
    t.string "ibrahim_eita_send_regards_renamed_by_noorelmobashar67"
    t.string "ibrahim_eita_send_regards_renamed_by_noorelmobashar68"
    t.string "ibrahim_eita_send_regards_renamed_by_noorelmobashar69"
    t.string "ibrahim_eita_send_regards_renamed_by_noorelmobashar70"
    t.string "ibrahim_eita_send_regards_renamed_by_noorelmobashar71"
    t.string "ibrahim_eita_send_regards_renamed_by_noorelmobashar72"
    t.string "ibrahim_eita_send_regards_renamed_by_noorelmobashar73"
    t.string "ibrahim_eita_send_regards_renamed_by_noorelmobashar74"
    t.string "ibrahim_eita_send_regards_renamed_by_noorelmobashar75"
    t.string "ibrahim_eita_send_regards_renamed_by_noorelmobashar76"
    t.string "ibrahim_eita_send_regards_renamed_by_noorelmobashar77"
    t.string "ibrahim_eita_send_regards_renamed_by_noorelmobashar78"
    t.string "ibrahim_eita_send_regards_renamed_by_noorelmobashar79"
    t.string "ibrahim_eita_send_regards_renamed_by_noorelmobashar80"
    t.string "ibrahim_eita_send_regards_renamed_by_noorelmobashar81"
    t.string "ibrahim_eita_send_regards_renamed_by_noorelmobashar82"
    t.string "ibrahim_eita_send_regards_renamed_by_noorelmobashar83"
    t.string "ibrahim_eita_send_regards_renamed_by_noorelmobashar84"
    t.string "ibrahim_eita_send_regards_renamed_by_noorelmobashar85"
    t.string "ibrahim_eita_send_regards_renamed_by_noorelmobashar86"
    t.string "ibrahim_eita_send_regards_renamed_by_noorelmobashar87"
    t.string "ibrahim_eita_send_regards_renamed_by_noorelmobashar88"
    t.string "ibrahim_eita_send_regards_renamed_by_noorelmobashar89"
    t.string "ibrahim_eita_send_regards_renamed_by_noorelmobashar90"
    t.string "ibrahim_eita_send_regards_renamed_by_noorelmobashar91"
    t.string "ibrahim_eita_send_regards_renamed_by_noorelmobashar92"
    t.string "ibrahim_eita_send_regards_renamed_by_noorelmobashar93"
    t.string "ibrahim_eita_send_regards_renamed_by_noorelmobashar94"
    t.string "ibrahim_eita_send_regards_renamed_by_noorelmobashar95"
    t.string "ibrahim_eita_send_regards_renamed_by_noorelmobashar96"
    t.string "ibrahim_eita_send_regards_renamed_by_noorelmobashar97"
    t.string "ibrahim_eita_send_regards_renamed_by_noorelmobashar98"
    t.string "ibrahim_eita_send_regards_renamed_by_noorelmobashar99"
    t.string "ibrahim_eita_send_regards_renamed_by_noorelmobashar100"
    t.string "ibrahim_eita_send_regards_renamed_by_noorelmobashar101"
    t.string "ibrahim_eita_send_regards_renamed_by_noorelmobashar102"
    t.string "ibrahim_eita_send_regards_renamed_by_noorelmobashar103"
    t.string "islam_khaled_war2"
    t.string "youssef2_renamed_by_karim_muhammad"
    t.string "amira_elsa3id_was_here"
    t.string "AmiraElsa3id"
    t.string "abdelhamid_renamed_by_shahd"
    t.string "ahmed_faheem_renamed_by_shahd"
    t.string "islam_khaled_war"
    t.string "deiaa_renamed_by_karim_muhammad"
    t.string "islam_khaled"
    t.string "maryamabdelraheem"
    t.string "mohamedHalawa"
    t.string "noorelmobashar_nickname_renamed_by_karim_muhammad"
    t.string "mohamed_renamed_by_karim_muhammad"
    t.string "karim_muhammad_renamed_by_waleed"
    t.string "keroraed_renamed_by_waleed"
    t.string "ramadan_mohamed"
    t.string "kerolosnashat_renamed_by_waleed"
    t.string "mohamedwaleed_renamed_by_karim_muhammad"
    t.string "kareem_sultan_defeated_by_abdelhamid"
    t.string "rehab_was_here"
    t.string "abdulrahman"
    t.string "amr_abokhaled"
    t.string "ebram"
    t.string "hatem"
    t.string "Tadros"
    t.string "mo_ali"
    t.string "Torl_Ali"
    t.string "nourhan"
    t.string "MO_conqueredSameh_Hashim_Andrewtate"
    t.string "JAWWWWWWWWWWWWWWWWWWWWWWWWWWWN"
    t.string "EhYabaByKhlil_isForAbdelhaqONLYYY"
    t.string "hamdonlostAgainstAbdelhaq"
    t.string "zeyadShahinWontBeEverSavedAgain"
    t.string "mohamedabdelhaq_renamed_by_rana"
    t.string "MoAbdelhaq_MoRamadan"
    t.string "khalil_hacked_zeyad_black_in_posts"
    t.string "smashed_by_hashing"
    t.string "EhYabaImMoabdelhaq"
    t.string "ahmed_ehab_farouk_eliminated_by_john_conquered_by_mohamed_sameh"
    t.string "HashingAbdulaziz_hacked_by_mostafa"
    t.string "khaled_checkpointed_by_karim"
    t.string "karim_bymasi_ala_kolo"
    t.string "karim_ibrahim_renamed_by_rana"
    t.string "ebrahimmostafa133"
    t.string "karim_bymasi_ala_kolo_2"
    t.string "abdulrahman_295"
  end

  create_table "students", force: :cascade do |t|
    t.string "name"
    t.integer "age"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.string "level"
    t.string "rahma_edited"
    t.string "amr_mohamed_shoukry_send_regards_zezo"
    t.string "Gamgoum"
    t.string "new_column"
    t.string "MoAbdelhaqHaveDoneItwithAsaad"
  end

  create_table "users", force: :cascade do |t|
    t.string "name"
    t.string "email"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.string "ibrahim_eita_send_regards_Mohamed_Hany_zagazigBranchEltop"
    t.string "ibrahim_eita_send_regards_Mohamed_Hany_mahalawy"
    t.string "ibrahim_eita_send_regards_Mohamed_Hany_mohamed"
    t.string "ibrahim_eita_send_regards_Mohamed_Hany_abdulrahmanIbrahim"
    t.string "ibrahim_eita_send_regards_Mohamed_Hany_sayed"
    t.string "ibrahim_eita_send_regards_khaledWin"
    t.string "ibrahim_eita_send_regards_Mohamed_Hany_amr"
    t.string "ibrahim_eita_send_regards_Mohamed_Hany_ayman_khaled"
    t.string "ibrahim_eita_send_regards_Mohamed_Hany_mohamed_hamdy"
    t.string "encrypted_password", default: "", null: false
    t.string "reset_password_token"
    t.datetime "reset_password_sent_at"
    t.datetime "remember_created_at"
    t.string "ibrahim_eita_send_regards_Mohamed_Hany_Ahmed_fathi"
    t.string "ibrahim_eita_send_regards_Mohamed_Hany_azab"
    t.string "ibrahim_eita_send_regards_Mohamed_Hany_khaldoun"
    t.string "ibrahim_eita_send_regards_Mohamed_Hany_nesma"
    t.string "mohamed_tarek_3"
    t.string "amira_elsa3id_strikes"
    t.string "amira_elsa3id_rules"
    t.string "amira_elsa3id_wins"
    t.string "ibrahim_eita_send_regards_mawadaelmeshad"
    t.string "ibrahim_eita_send_regards_ahmed_ibrahim_elemam"
    t.string "ibrahim_eita_send_regards_ahmed_mohammed_mostafa"
    t.string "ibrahim_eita_send_regards_mohamedabdelshakor"
    t.string "ibrahim_eita_send_regards_mostafa_abdelmajied"
    t.string "ibrahim_eita_send_regards_maryam"
    t.string "ibrahim_eita_send_regards_shaza"
    t.string "ibrahim_eita_send_regards_karim_kadry_war"
    t.string "ibrahim_eita_send_regards_mohamed_reda_mohamed"
    t.string "ibrahim_eita_send_regards_amr_mohamed_shoukry"
    t.string "ibrahim_eita_send_regards_shaza_elshimy"
    t.string "ibrahim_eita_send_regards_mohamedHalawa"
    t.string "ibrahim_eita_send_regards_maryamabdelraheem"
    t.string "ibrahim_eita_send_regards_kero_ayman34"
    t.string "ibrahim_eita_send_regards_shaza_hamdy_elshimy"
    t.string "ibrahim_eita_send_regards_mohamed_abdo"
    t.string "ibrahim_eita_send_regards_nancy"
    t.string "ibrahim_eita_send_regards_mostafa_mohamed_salah"
    t.string "HashimAbdulaziz"
    t.string "AndMoAbdelhaqConqueredMuhanad"
    t.string "shahd"
    t.index ["email"], name: "index_users_on_email", unique: true
    t.index ["reset_password_token"], name: "index_users_on_reset_password_token", unique: true
  end

end
