# This file is auto-generated from the current state of the database. Instead
# of editing this file, please use the migrations feature of Active Record to
# incrementally modify your database, and then regenerate this schema definition.
#
# This file is the source Rails uses to define your schema when running `bin/rails
# db:schema:load`. When creating a new database, `bin/rails db:schema:load` tends to
# be faster and is potentially less error prone than running all of your
# migrations from scratch. Old migrations may fail to apply correctly if those
# migrations use external dependencies or application code.
#
# It's strongly recommended that you check this file into your version control system.

ActiveRecord::Schema[7.1].define(version: 2026_06_13_094344) do
  create_table "posts", force: :cascade do |t|
    t.string "renamed_by_noorelmobashar0"
    t.string "renamed_by_noorelmobashar1"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.string "renamed_by_noorelmobashar2"
    t.string "renamed_by_noorelmobashar3"
    t.string "renamed_by_noorelmobashar4"
    t.string "renamed_by_noorelmobashar5"
    t.string "renamed_by_noorelmobashar6"
    t.string "renamed_by_noorelmobashar7"
    t.string "renamed_by_noorelmobashar8"
    t.string "renamed_by_noorelmobashar9"
    t.string "renamed_by_noorelmobashar10"
    t.string "renamed_by_noorelmobashar11"
    t.string "renamed_by_noorelmobashar12"
    t.string "renamed_by_noorelmobashar13"
    t.string "renamed_by_noorelmobashar14"
    t.string "renamed_by_noorelmobashar15"
    t.string "renamed_by_noorelmobashar16"
    t.string "renamed_by_noorelmobashar17"
    t.string "renamed_by_noorelmobashar18"
    t.string "renamed_by_noorelmobashar19"
    t.string "renamed_by_noorelmobashar20"
    t.string "renamed_by_noorelmobashar21"
    t.string "renamed_by_noorelmobashar22"
    t.string "renamed_by_noorelmobashar23"
    t.string "renamed_by_noorelmobashar24"
    t.string "renamed_by_noorelmobashar25"
    t.string "renamed_by_noorelmobashar26"
    t.string "renamed_by_noorelmobashar27"
    t.string "renamed_by_noorelmobashar28"
    t.string "renamed_by_noorelmobashar29"
    t.string "renamed_by_noorelmobashar30"
    t.string "renamed_by_noorelmobashar31"
    t.string "renamed_by_noorelmobashar32"
    t.string "renamed_by_noorelmobashar33"
    t.string "renamed_by_noorelmobashar34"
    t.string "renamed_by_noorelmobashar35"
    t.string "renamed_by_noorelmobashar36"
    t.string "renamed_by_noorelmobashar37"
    t.string "renamed_by_noorelmobashar38"
    t.string "renamed_by_noorelmobashar39"
    t.integer "renamed_by_noorelmobashar40"
    t.string "renamed_by_noorelmobashar41"
    t.string "renamed_by_noorelmobashar42"
    t.string "renamed_by_noorelmobashar43"
    t.string "renamed_by_noorelmobashar44"
    t.string "renamed_by_noorelmobashar45"
    t.string "renamed_by_noorelmobashar46"
    t.string "renamed_by_noorelmobashar47"
    t.string "renamed_by_noorelmobashar48"
    t.string "renamed_by_noorelmobashar49"
    t.string "renamed_by_noorelmobashar50"
    t.string "renamed_by_noorelmobashar51"
    t.string "renamed_by_noorelmobashar52"
    t.string "renamed_by_noorelmobashar53"
    t.string "renamed_by_noorelmobashar54"
    t.string "renamed_by_noorelmobashar55"
    t.string "renamed_by_noorelmobashar56"
    t.string "renamed_by_noorelmobashar57"
    t.string "renamed_by_noorelmobashar58"
    t.string "renamed_by_noorelmobashar59"
    t.string "renamed_by_noorelmobashar60"
    t.string "renamed_by_noorelmobashar61"
    t.string "renamed_by_noorelmobashar62"
    t.string "renamed_by_noorelmobashar63"
    t.string "renamed_by_noorelmobashar64"
    t.string "renamed_by_noorelmobashar65"
    t.string "renamed_by_noorelmobashar66"
    t.string "renamed_by_noorelmobashar67"
    t.string "renamed_by_noorelmobashar68"
    t.string "renamed_by_noorelmobashar69"
    t.string "renamed_by_noorelmobashar70"
    t.string "renamed_by_noorelmobashar71"
    t.string "renamed_by_noorelmobashar72"
    t.string "renamed_by_noorelmobashar73"
    t.string "renamed_by_noorelmobashar74"
    t.string "renamed_by_noorelmobashar75"
    t.string "renamed_by_noorelmobashar76"
    t.string "renamed_by_noorelmobashar77"
    t.string "renamed_by_noorelmobashar78"
    t.string "renamed_by_noorelmobashar79"
    t.string "renamed_by_noorelmobashar80"
    t.string "renamed_by_noorelmobashar81"
    t.string "renamed_by_noorelmobashar82"
    t.string "renamed_by_noorelmobashar83"
    t.string "renamed_by_noorelmobashar84"
    t.string "renamed_by_noorelmobashar85"
    t.string "renamed_by_noorelmobashar86"
    t.string "renamed_by_noorelmobashar87"
    t.string "renamed_by_noorelmobashar88"
    t.string "renamed_by_noorelmobashar89"
    t.string "renamed_by_noorelmobashar90"
    t.string "renamed_by_noorelmobashar91"
    t.string "renamed_by_noorelmobashar92"
    t.string "ahmed_fathi93"
    t.string "ahmed_fathi94"
    t.string "ahmed_fathi95"
    t.string "ahmed_fathi96"
    t.string "ahmed_fathi97"
    t.string "ahmed_fathi98"
    t.string "Mohamed_Hany_ahmed_fathi99"
    t.string "ahmedwagih100_war"
    t.string "ahmed_wagih111"
    t.string "amir_mawla_3_war"
    t.string "abdo_war"
    t.string "ahmed2"
    t.string "youssef2"
    t.string "rana_hany"
  end

  create_table "students", force: :cascade do |t|
    t.string "name"
    t.integer "age"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.string "level"
    t.string "rahma_edited"
    t.string "zezo"
    t.string "Gamgoum"
    t.string "new_column"
  end

  create_table "users", force: :cascade do |t|
    t.string "name"
    t.string "email"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.string "Mohamed_Hany_zagazigBranchEltop"
    t.string "Mohamed_Hany_mahalawy"
    t.string "Mohamed_Hany_mohamed"
    t.string "Mohamed_Hany_abdulrahmanIbrahim"
    t.string "Mohamed_Hany_sayed"
    t.string "Mohamed_Hany_mokhtar"
    t.string "Mohamed_Hany_amr"
    t.string "Mohamed_Hany_ayman_khaled"
    t.string "Mohamed_Hany_mohamed_hamdy"
    t.string "encrypted_password", default: "", null: false
    t.string "reset_password_token"
    t.datetime "reset_password_sent_at"
    t.datetime "remember_created_at"
    t.string "Mohamed_Hany_Ahmed_fathi"
    t.string "Mohamed_Hany_azab"
    t.string "Mohamed_Hany_khaldoun"
    t.string "Mohamed_Hany_nesma"
    t.string "sohyla"
    t.string "mahmoud"
    t.index ["email"], name: "index_users_on_email", unique: true
    t.index ["reset_password_token"], name: "index_users_on_reset_password_token", unique: true
  end

end
